version: '3'

services:
  notes:
    image: backend:1.1
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
    depends_on:
      - mongo
    
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config: